[[redirects]]
from = "/2011/09/22/better-infinite-scrolling-with-the-html5-history-api"
to = "/blog/2011/09/22/better-infinite-scrolling-with-the-html5-history-api/"
status = 301
force = true

[[redirects]]
from = "/post/261593774"
to = "/blog/2009/11/29/the-star-wars-opening-crawl-in-html-and-css/"
status = 301
force = true

[[redirects]]
from = "/post/261593774/*"
to = "/blog/2009/11/29/the-star-wars-opening-crawl-in-html-and-css/"
status = 301
force = true

[[redirects]]
from = "/post/475773360/*"
to = "/blog/2010/03/26/css-glow-effects-with-box-shadow/"
status = 301
force = true

[[redirects]]
from = "/post/84438959/*"
to = "/blog/2009/03/07/start-bittorrent-downloads-remotely-with-dropbox/"
status = 301
force = true

[[redirects]]
from = "/post/36097597/*"
to = "/blog/2008/04/08/helvetica-neue-light/"
status = 301
force = true

[[redirects]]
from = "/2011/09/25/i-love-chromes-automatic-updates"
to = "/blog/2011/09/25/i-love-chromes-automatic-updates"
status = 301
force = true

[[redirects]]
from = "/experiments/clock.html"
to = "https://codepen.io/gesteves/full/ZwmrzO"
status = 301
force = true

[[redirects]]
from = "/experiments/timer.html"
to = "https://codepen.io/gesteves/full/bzQLdX"
status = 301
force = true

[[redirects]]
from = "/experiments/starwars.html"
to = "https://codepen.io/gesteves/full/YBPpwG"
status = 301
force = true

[[redirects]]
from = "/portfolio"
to = "/"
status = 301
force = true

[[redirects]]
from = "/experiments"
to = "/"
status = 301
force = true

[[redirects]]
from = "/help"
to = "/"
status = 301
force = true

[[redirects]]
from = "/es*"
to = "/"
status = 301
force = true

[[redirects]]
from = "https://blog.gesteves.com/*"
to = "https://www.gesteves.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://gesteves.netlify.com/*"
to = "https://www.gesteves.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://photo.gesteves.com/*"
to = "https://www.allencompassingtrip.com/:splat"
status = 301
force = true

[[redirects]]
from = "/atom.xml"
to = "https://www.allencompassingtrip.com/feed"
status = 301
force = true
